// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp72DyokYR_8LONMhKQdtrdNf3v-JPSLc',
    appId: '1:647738673433:web:cc8505a132b731051cdd88',
    messagingSenderId: '647738673433',
    projectId: 'boibitan-app',
    authDomain: 'boibitan-app.firebaseapp.com',
    storageBucket: 'boibitan-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBziNAwTmGKDlXIY4ulgvxiz6m9enwBbw',
    appId: '1:647738673433:android:c33d538f94dce21e1cdd88',
    messagingSenderId: '647738673433',
    projectId: 'boibitan-app',
    storageBucket: 'boibitan-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjTxiwGQGcSgGjOYYatxniKjw6Zppj82Q',
    appId: '1:647738673433:ios:a1a9fc33da6df5ed1cdd88',
    messagingSenderId: '647738673433',
    projectId: 'boibitan-app',
    storageBucket: 'boibitan-app.firebasestorage.app',
    iosBundleId: 'com.boibitan.boiBitan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjTxiwGQGcSgGjOYYatxniKjw6Zppj82Q',
    appId: '1:647738673433:ios:a1a9fc33da6df5ed1cdd88',
    messagingSenderId: '647738673433',
    projectId: 'boibitan-app',
    storageBucket: 'boibitan-app.firebasestorage.app',
    iosBundleId: 'com.boibitan.boiBitan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp72DyokYR_8LONMhKQdtrdNf3v-JPSLc',
    appId: '1:647738673433:web:59d249f100d9c44e1cdd88',
    messagingSenderId: '647738673433',
    projectId: 'boibitan-app',
    authDomain: 'boibitan-app.firebaseapp.com',
    storageBucket: 'boibitan-app.firebasestorage.app',
  );
}
